# SITE CONFIGURATION
#title: Grimlight # your site title
author: Hjalmar Thulin
description: > # Meta description of Homepage
  Miniature lighting for all shapes

#baseurl: "/hka/gamma" # the subpath of your site, e.g. /blog
#baseurl: ""
#url: "https://aelv.se"
#url: "https://grimlight.se"
url: "http://grimlight.github.io"
baseurl: "grimlight.github.io/"

# SEO PLUGIN
social:
  name: Grimlight Media
  links:
    - https://twitter.com/grimlightmedia
    - https://www.facebook.com/grimlightmedia/
    - https://www.instagram.com/grimlight.miniature.lighting/

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'Store', link: '/store'}
  - {name: 'Guides', link: '/guides'}    
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}
  - {name: 'Showcase', link: 'https://www.instagram.com/grimlight.miniature.lighting/'}  

#tagline: >
#  Miniature lighting for all shapes.

hero_img: posts/gl.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: media@grim-light.se # email for form submission

facebook_username: grimlightmedia
twitter_username: grimlightmedia
github_username:  GLMiniatyrdesign
instagram_username: grimlight.miniature.lighting # replace with your_instagram_username or comment to remove link from footer

#disqus:
#  shortname: janczizikow # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
